### PR TITLE
Prepare for Renovate with reusable workflows

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Adding Renovate to Laminas, Mezzio repositories. https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

- Configure minimum supported PHP version
- Update composer dependencies
- Update to reusable `Continuous Integration` workflow
- Update to reusable `Automatic Releases` workflow

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Requires rolling back to a much smaller `composer.lock` change (just hash change)

**Review by Ocramius — APPROVED** [review]
LGTM, but tests fail on silly thresholds due to integration scenarios running on the (very busy) workers

**Comment by Ocramius** [comment]
We should probably adjust this a bit to match (and replace) https://github.com/laminas/laminas-diagnostics/blob/4f6c493e9d6fa57f29d32671a4a86e841afd9428/.github/workflows/unit-tests.yml#L1 ? 

We need services to be running in general, for this to work :thinking:

**Comment by ghostwriter** [comment]
the `services` keyword is not supported yet for reusable workflows.

https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow

**Comment by weierophinney** [comment]
@ghostwriter I'm working on the conflict; need to resolve issues with the coding standard first (PR incoming...). I'll take it from here.

**Comment by Ocramius** [comment]
Target branch was wrong here :thinking:

**Comment by Ocramius** [comment]
markdownlint failures unrelated, caused by current ongoing Russian invasion of Ukraine. This patch is ready to go, thanks @ghostwriter @weierophinney!

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Gonna release this one: lots of changes/improvements in `1.15.0`, and it's best to have it tried out in the field too.

**Pull request merged**
