### PR TITLE
Add support for `php-amqplib:^3.0`

### PR DESCRIPTION
**Pull request by sbacelic**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Summary

AMQPConnection used in RabbitMQ check has been removed in php-amqplib v3: https://github.com/php-amqplib/php-amqplib/pull/897 so I added support for it.

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Any chance of getting this released? php-amqplib 3.0 is required for using PHP 8

**Comment by sbacelic** [comment]
> Any chance of getting this released? php-amqplib 3.0 is required for using PHP 8

@REBELinBLUE you can fork this PR or use the forked version in composer.json until this is not resolved:

```  
"repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/sbacelic/laminas-diagnostics"
        }
    ],
  ...
  "laminas/laminas-diagnostics": "1.9.x-dev"
```

**Comment by REBELinBLUE** [comment]
for now I have added the following file

```
<?php

declare(strict_types=1);

namespace PhpAmqpLib\Connection;

// FIXME: Remove this once https://github.com/laminas/laminas-diagnostics/pull/22 has been released and
// https://github.com/liip/LiipMonitorBundle has been updated
class AMQPConnection extends AMQPStreamConnection
{
}
```

to my code and added it to the autoloader classmap, because it would still require `LiipMonitorBundle` to be updated to use the new version of this library.

**Review by Ocramius — APPROVED** [review]
Thanks @sbacelic!

**Pull request merged**
