### PR TITLE
Fixes #12 PHP 8.0 support

### LINKED ISSUE #12: PHP 8.0 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by samsonasik** [comment]
travis build not started ?

**Comment by samsonasik** [comment]
@boesing any way to exclude services (memcached, mongodb, redis-server) in php 8 in travis config ?

**Comment by samsonasik** [comment]
it seems php 7.3 not support memcache as well in travis:

```bash
.php: symbol lookup error: /home/travis/.phpenv/versions/7.3.23/lib/php/extensions/no-debug-zts-20180731/memcache.so: undefined symbol: mmc_queue_po
```

**Comment by samsonasik** [comment]
progress, error in php 8: 

```bash
There were 2 errors:

1) LaminasTest\Diagnostics\ChecksTest::testRabbitMQ

Required parameter $io follows optional parameter $vhost

/home/travis/build/laminas/laminas-diagnostics/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:175

/home/travis/build/laminas/laminas-diagnostics/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php:6

/home/travis/build/laminas/laminas-diagnostics/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php:11

/home/travis/build/laminas/laminas-diagnostics/src/Check/RabbitMQ.php:74

/home/travis/build/laminas/laminas-diagnostics/test/ChecksTest.php:74

2) LaminasTest\Diagnostics\RunnerTest::testPHPWarningResultsInFailure

ArgumentCountError: strpos() expects at least 2 arguments, 0 given

/home/travis/build/laminas/laminas-diagnostics/test/TestAsset/Check/TriggerWarning.php:18

/home/travis/build/laminas/laminas-diagnostics/src/Runner/Runner.php:122

/home/travis/build/laminas/laminas-diagnostics/test/RunnerTest.php:307

--

There was 1 failure:

1) LaminasTest\Diagnostics\ChecksTest::testMongo

Failed asserting that Laminas\Diagnostics\Result\Failure Object (...) is an instance of class "Laminas\Diagnostics\Result\Success".

/home/travis/build/laminas/laminas-diagnostics/test/ChecksTest.php:138
```

**Comment by samsonasik** [comment]
It seems not as easy as I imagine, closing for now in case other will try.

**Comment by boesing** [comment]
Hm, maybe we can install missing extensions by using pecl?

There are some tricks to use pecl in non-interactive shells (using some echo and piping that to `pecl install`).
`laminas-cache` was doing that lately and I've moved that to the satellites:

https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/a306d94cf804b509c4da6c2b81ce872f53b2a673/.travis.yml#L74

**Comment by samsonasik** [comment]
@boesing thank you, I will retry when I have a chance. Feel free If anyone want to give a try.

**Pull request closed without merging**
