### PR TITLE
Add support for PHP 8.4.0

### PR DESCRIPTION
**Pull request by mkoprek**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | yes
| New Feature   | no
| RFC           |  no
| QA            |  no

### CODE REVIEW

**Comment by mkoprek** [comment]
Waiting for: https://github.com/laminas/laminas-loader/pull/13

**Comment by alexmerlin** [comment]
@mkoprek PHP 8.4 support added in https://github.com/laminas/laminas-loader/releases/tag/2.11.0

**Comment by mkoprek** [comment]
I don't have idea why it output so many error at PHPUnit 8.4 lowest. It requires specific knowledge in CI configuration which I don't have. Maybe someone can help with it?

**Comment by gsteel** [comment]
> I don't have idea why it output so many error at PHpUnit 8.4 lowest. It requires specific knowledge in CI configuration which I don't have. Maybe someone can help with it?

To begin with run `composer update; composer bump -D` locally to bump dev dependencies to the latest supported releases and push again to run CI.

Many of the issues here are incompatibilities with PHPUnit and 8.4

**Comment by alexmerlin** [comment]
Try adding [.laminas-ci.json](https://github.com/laminas/laminas-mvc-i18n/blob/1.10.x/.laminas-ci.json).
With this, platform dependencies will be ignored - this was done in other packages as well to fix the issue until PHP 8.4 is officially released.

**Comment by mkoprek** [comment]
@alexmerlin I've added `ignore_php_platform_requirements` to `.laminas-ci.json`. There are still same errors, any other idea?

**Comment by mkoprek** [comment]
> To begin with run composer update; composer bump -D locally to bump dev dependencies to the latest supported releases and push again to run CI.
> 
> Many of the issues here are incompatibilities with PHPUnit and 8.4

I don't think it will help in this case. Dependencies are right now in almost newest versions.

**Comment by gsteel** [comment]
> I don't think it will help in this case. Dependencies are right now in almost newest versions.

I do think it will help in this case because deps are not almost newest when testing on lowest 🤷‍♂️

**Comment by mkoprek** [comment]
@gsteel You was right. I was sure CI is working in other way. 

There is last unit test to fix, maybe I will try to fix it at the weekend.

**Comment by alexmerlin** [comment]
@mkoprek Any progress with fixing the tests?

**Comment by mkoprek** [comment]
@alexmerlin sorry, didn't have time for it yet. 

Maybe someone else can move it forward?

**Comment by mkoprek** [comment]
@alexmerlin Maybe not the fastest, but it finally worked out.

Waiting for some CR

**Review by alexmerlin — APPROVED** [review]
LGTM! 👍

**Comment by mkoprek** [comment]
@Ocramius Hey, could you please take a look?

**Comment by matjanis1992** [comment]
@mkoprek @Ocramius Hey, any chance you guys could push this a bit? Seems like everything is already there.

**Comment by mkoprek** [comment]
Unfortunately, I do not have the permissions.

**Comment by alexmerlin** [comment]
@gsteel Do you have anything to add to this or we can merge it?

**Review by gsteel — APPROVED** [review]
LGTM 👍 Thanks @mkoprek

**Pull request merged**
